version: '3.8'
services:
  web:
    build: .
    environment:
      FLASK_APP: src/app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
