"""add_death_cascade_for_messages_in_chat

Revision ID: 1d084672b1cc
Revises: 96e75f246bf7
Create Date: 2024-03-15 11:56:20.140674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d084672b1cc'
down_revision: Union[str, None] = '96e75f246bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
