"""Initial database migration

Revision ID: 97cc0fc604ad
Revises: 1d084672b1cc
Create Date: 2024-03-15 13:05:41.715241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cc0fc604ad'
down_revision: Union[str, None] = 'bfe7cab56480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
